
project_id = "gsiahmdrzkuujzbzvfsi"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[functions.ensure-storage-bucket]
verify_jwt = true
