// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsiahmdrzkuujzbzvfsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzaWFobWRyemt1dWp6Ynp2ZnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjc4MzYsImV4cCI6MjA1Nzk0MzgzNn0.-Gw6hInuc5GaA4ItQH12QA0yiUEr5lRkIHXMR0J6DDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);